### ISSUE TITLE
Take this repo out of the seed-repo job

### ISSUE THREAD

**Issue by arschles** [deis/steward-cf#3]
https://github.com/deis/seed-repo

**Comment by krancour** [comment]
So... it's not actually in there. I added it to seed-repo locally so that I could easily create all the labels. I never committed / PR'ed those changes. I manually cleaned up the 2.8 and 2.9 (workflow) milestones that got created. So I think this is all set.

**Comment by arschles** [comment]
Got it, thanks for the explanation; closing
